### ISSUE TITLE
Meta: Improved URL parameters and link sharing

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2025]
We want to improve URL support in Studio (GET parameters / deep links), so that users can bookmark or share the current URL and persist their current layout/connection/timestamp. We also want to make it easier for users to open a web link in their desktop app.

See: [Requirements doc](https://docs.google.com/document/d/1jULICvQaZbJM8Et4ylFCE7GIFwedq7YkB4NhvnpjW0k/edit)

- [x] https://github.com/foxglove/studio/issues/1868
- [x] https://github.com/foxglove/studio/issues/1911
- [x] https://github.com/foxglove/studio/issues/1960

**Comment by itsderek23** [comment]
This would be great. I'd love to drop a link into Slack that opens a FoxGlove Studio window w/the same panels, bag (loaded via the data platform), and at the same point in time.
