### ISSUE TITLE
Improve new user experience

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2148]
Our current welcome layout is pretty overwhelming. We should provide a nicer first-run experience, showing the power of studio and also walking users through some basic things they can do.

- [x] Add "Explore sample data" button (https://github.com/foxglove/studio/pull/2362)
- [x] https://github.com/foxglove/studio/pull/2388
- [x] Data Source sidebar should should remain open even after selecting a data source.
- [x] When clicking "Data source" icon in sidebar - if no connection is present - open the "Open Dialog" immediately. This creates a 1-click open to select a data source. Open the sidebar as well. https://github.com/foxglove/studio/pull/2360
- [x] https://github.com/foxglove/studio/pull/2362
- [x] [Bug] Opening a link from Data Platform should not show the Open dialog
- [x] Change "Current Connection" in sidebar to be "Current data source"
- [x] https://github.com/foxglove/studio/pull/2361
- [x] Remove opening the Open Dialog when clicking the connection sidebar icon
- [x] add date to start/end time #2424 
- [x] Open Command Button hover state #2428
- [x] Rename `Start` to `Open data source`, rename modal heading to `Get started`. Consider adding emojis. #2428
- [x] #2419
- [x] Middle-truncate the data source name (e.g. remote bag URL) #2428
- [x] #2420
- [x] #2421
- [x] fix bottom padding for very short windows #2428
- [x] Update slack link to `https://foxglove.dev/slack` #2428
- [x] https://github.com/foxglove/studio/issues/2417 @defunctzombie 
- [x] #2431
- [x] #2443

pre or post release

- [x] #2537
- [x] #2532
- [x] https://github.com/foxglove/studio/pull/2628
- [ ] #2629
- [ ] ~~Add `Type` at the top of Data Source sidebar~~
- [ ] ~~Remove start/end/duration for live connections~~
- [x] #2589
- [x] https://github.com/foxglove/studio/pull/2548
- [x] #2564
- [x] https://github.com/foxglove/studio/pull/2448

post studio release

- [x] https://github.com/foxglove/studio/pull/2530
- [x] https://github.com/foxglove/studio/pull/2529
- [x] https://github.com/foxglove/studio/pull/2528
- [x] https://github.com/foxglove/studio/pull/2527
- [x] https://github.com/foxglove/studio/pull/2526
- [x] https://github.com/foxglove/studio/pull/2525
- [x] #2578

**Comment by defunctzombie** [comment]
Idea: remove the welcome panel and replace it with a modal that shows on first run. The modal can be one of those carousel UI patterns so the user can scroll through some screens with app features.

**Comment by defunctzombie** [comment]
In-app feedback.

**Comment by defunctzombie** [comment]
@amacneil `Refreshing page with a local bag file loaded should keep that bag file loaded`

It is a browser limitation that we must ask for user consent before we have access on refresh. If we are ok with that - then the ask here is that we remember that you have a local file open and automatically ask for consent? Similar to how we remember connection based data sources and try to reconnect when they are specific in the url args?

**Comment by amacneil** [comment]
Yeah I think that (asking for consent on refresh) would be better than dumping the user back onto the welcome dialog.

**Comment by defunctzombie** [comment]
@amacneil I've removed `- [ ] Refreshing page with a local bag file loaded should keep that bag file loaded` to bring down the scope of this issue. We have the recents list which is working well. I don't believe this specific issue is that impactful to new user experience.

**Comment by amacneil** [comment]
👍 Maybe it's not part of the new user experience, but seems still worth creating a separate ticket for? Refreshing seems fairly common with our users (if they are encountering unexpected issues/errors). Could we keep some sort of reference (even if opaque identifier) in the URL to facilitate that?

**Comment by defunctzombie** [comment]
@amacneil we can definitely make this work - I just wanted to scope it out of this work so we can have a finite set of things we are trying to finish here.

I agree refreshing is common - I certainly do it all the time with development - but I've also found that the recents list has made me 99% happy when I refresh and can click the first item so think the additional win is low for local files right now.

**Comment by defunctzombie** [comment]
> * Remove start/end/duration for live connections

For now the end time here is the only place a user can see the current timestamp since we do not show any playback controls. So we should keep these and revisit later.
